AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  traininstance:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 60
      Role: 'arn:aws:iam::463669532088:role/service-role/train-instance-role-fduwx4gf'
      Layers:
        - 'arn:aws:lambda:us-east-2:463669532088:layer:my_pil:1'
        - 'arn:aws:lambda:us-east-2:934676248949:layer:pytorchv1-py36:2'
