AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  processsnapshot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 180
      Role: >-
        arn:aws:iam::463669532088:role/service-role/process-snapshot-role-t6gjtjt4
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /process-snapshot
            Method: POST
      Layers:
        - 'arn:aws:lambda:us-east-2:463669532088:layer:my_pil:1'
        - 'arn:aws:lambda:us-east-2:934676248949:layer:pytorchv1-py36:2'
